resources:
  - deployment.yaml
  - build-deployment.yaml
configMapGenerator:
  - name: light-knowledge-worker-config
    files:
      - ../config/worker.yml
      - ../config/startup.yml
      - ../config/server.yml
