apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: light-knowledge-admin-private
spec:
  podSelector:
    matchLabels: {app: light-knowledge-admin}
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels: {app: genai-query}
        - podSelector:
            matchLabels: {app: genai-command}
      ports:
        - {protocol: TCP, port: 8093}
    - from:
        - namespaceSelector:
            matchLabels: {kubernetes.io/metadata.name: monitoring}
          podSelector:
            matchLabels: {app.kubernetes.io/name: prometheus}
      ports:
        - {protocol: TCP, port: 8093}
