apiVersion: v1
kind: Service
metadata:
  name: light-knowledge-admin
spec:
  type: ClusterIP
  selector: {app: light-knowledge-admin}
  ports:
    - {name: http-admin, port: 8093, targetPort: http-admin}
