apiVersion: v1
kind: Secret
metadata:
  name: ${name:light-agent-account}-secret
  namespace: ${namespace:light-agent}
  labels:
    app.kubernetes.io/name: ${name:light-agent-account}
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: lightapi
type: Opaque
stringData:
  light-portal-authorization: ${lightPortalAuthorization:}
  light-4j-config-password: ${light4jConfigPassword:DEV}
  light-agent-host-id: ${lightAgentHostId}
  light-agent-agent-def-id: ${lightAgentDefId}
  database-url: ${database.url}
data:
  ca.pem: ${bootstrapCaPemBase64}
