apiVersion: v1
kind: Service
metadata:
  name: ${name:light-agent-account}
  namespace: ${namespace:light-agent}
  labels:
    app.kubernetes.io/name: ${name:light-agent-account}
    app.kubernetes.io/component: agent
    app.kubernetes.io/part-of: lightapi
spec:
  type: ${service.type:ClusterIP}
  selector:
    app.kubernetes.io/name: ${name:light-agent-account}
  ports:
    - name: http
      port: ${service.httpPort:8083}
      targetPort: http
      protocol: TCP
    - name: https
      port: ${service.httpsPort:8443}
      targetPort: https
      protocol: TCP
