tls:
  verifyHostname: ${client.verifyHostname:true}
  caCertPath: ${client.caCertPath:}
oauth:
  token:
    key:
      server_url: ${client.tokenKeyServerUrl:https://light-oauth:6881}
      serviceId: ${client.tokenKeyServiceId:}
      uri: ${client.tokenKeyUri:/oauth2/AZZRJE52eXu3t1hseacnGQ/keys}
      client_id: ${client.tokenKeyClientId:}
      client_secret: ${client.tokenKeyClientSecret:}
      serviceIdAuthServers: ${client.tokenKeyServiceIdAuthServers:{}}
      enableHttp2: ${client.tokenKeyEnableHttp2:true}
      audience: ${client.tokenKeyAudience:}
request:
  connectTimeout: ${client.connectTimeout:2000}
  timeout: ${client.timeout:4000}
