portalUrl: ${portalRegistry.portalUrl:https://controller:8438}
portalQueryUrl: ${portalQuery.url:https://controller:8438}
portalToken: ${LIGHT_PORTAL_AUTHORIZATION:}
controllerDiscoveryToken: ${portalRegistry.controllerDiscoveryToken:}
