use agent_runtime_protocol::canonical_digest;
use light_agent::agent_config::AgentPolicy;

// Generated by AgentPolicyProjectionCompilerTest with -Dagent.turn.fixture=...
#[test]
fn java_turn_policy_publication_preserves_rust_signed_material() {
    let fixture: serde_json::Value =
        serde_json::from_str(include_str!("fixtures/portal-turn-policy-publication.json")).unwrap();
    let mut policy: AgentPolicy = serde_json::from_value(fixture["agentPolicy"].clone()).unwrap();
    assert_eq!(canonical_digest(&policy).unwrap(), fixture["contentDigest"]);
    let turn_policy = policy.execution.turn_policy.as_ref().unwrap();
    turn_policy
        .validate(policy.execution.coding_profile.is_some())
        .unwrap();
    assert_eq!(turn_policy.allowed_turn_types, ["coding"]);
    assert_eq!(turn_policy.default_turn_type, "coding");
    assert_eq!(
        policy
            .execution
            .coding_profile
            .as_ref()
            .unwrap()
            .product_profile_digest,
        policy.policy_snapshot.product_profile_digest
    );
    // The runtime verifies the full canonical content digest. Publisher subdigests
    // retain their older serialization contract (which omits null map values).
    policy
        .execution
        .turn_policy
        .as_mut()
        .unwrap()
        .allowed_turn_types
        .push("chat".into());
    assert_ne!(canonical_digest(&policy).unwrap(), fixture["contentDigest"]);
}
