use agent_runtime_protocol::canonical_digest;
use coding_agent_runtime::CodingAdapterContract;
use light_agent::agent_config::AgentPolicy;

// Generated by AgentPolicyProjectionCompilerTest in sibling light-portal with
// -Dagent.coding.fixture=/tmp/agent-coding-profile-java.json. Digests in this
// fixture are synthetic; this checks serialization, not live qualification.
#[test]
fn java_coding_publication_preserves_rust_content_and_contract_digests() {
    let fixture: serde_json::Value =
        serde_json::from_str(include_str!("fixtures/portal-coding-publication.json")).unwrap();
    let policy: AgentPolicy = serde_json::from_value(fixture["agentPolicy"].clone()).unwrap();
    assert_eq!(canonical_digest(&policy).unwrap(), fixture["contentDigest"]);
    let profile = policy.execution.coding_profile.as_ref().unwrap();
    let contract = CodingAdapterContract {
        schema_version: profile.schema_version,
        adapter_id: profile.adapter_id.clone(),
        adapter_version: profile.adapter_version.clone(),
        adapter_protocol_version: profile.adapter_protocol_version.clone(),
        action_kind: profile.action_kind.clone(),
        compatibility_digest: profile.compatibility_digest.clone(),
        image_digest: profile.image_digest.clone(),
        capability_digest: profile.capability_digest.clone(),
        template_id: profile.template_id.clone(),
        template_version: profile.template_version,
        template_digest: profile.template_digest.clone(),
        executable: profile.executable.clone(),
        binary_digest: profile.binary_digest.clone(),
        schema_digest: profile.schema_digest.clone(),
        required_features: profile.required_features.clone(),
    };
    assert_eq!(
        Some(contract.digest().unwrap()),
        profile.qualification.contract_digest
    );
}

#[test]
fn java_workspace_bindings_preserve_rust_signed_profile_and_legacy_absence() {
    let fixture: serde_json::Value = serde_json::from_str(include_str!(
        "fixtures/portal-workspace-coding-profile.json"
    ))
    .unwrap();
    let profile: light_agent::agent_config::CodingProfilePolicy =
        serde_json::from_value(fixture["profile"].clone()).unwrap();
    assert_eq!(serde_json::to_value(&profile).unwrap(), fixture["profile"]);
    assert_eq!(canonical_digest(&profile).unwrap(), fixture["digest"]);
    assert_eq!(profile.workspace_bindings.len(), 1);
    profile.workspace_bindings[0].validate().unwrap();
    let mut legacy = fixture["profile"].clone();
    legacy.as_object_mut().unwrap().remove("workspaceBindings");
    let old: light_agent::agent_config::CodingProfilePolicy =
        serde_json::from_value(legacy.clone()).unwrap();
    assert!(
        !serde_json::to_value(old)
            .unwrap()
            .as_object()
            .unwrap()
            .contains_key("workspaceBindings")
    );
}
