enabled: ${access-control.enabled:false}
accessRuleLogic: ${access-control.accessRuleLogic:any}
defaultDeny: ${access-control.defaultDeny:true}
defaultInclude: ${access-control.defaultInclude:false}
skipPathPrefixes: ${access-control.skipPathPrefixes:[]}
claimMappings: ${access-control.claimMappings:{}}
