enabled: ${handler.enabled:true}
reportHandlerDuration: ${handler.reportHandlerDuration:false}
handlerMetricsLogLevel: ${handler.handlerMetricsLogLevel:DEBUG}
basePath: ${handler.basePath:/}

handlers: ${handler.handlers:[]}

chains: ${handler.chains:{}}

paths: ${handler.paths:[]}

defaultHandlers: ${handler.defaultHandlers:[]}
