startup.bootstrapCaCertPath: config/ca.pem
client.caCertPath: config/ca.pem

handler.handlers:
  - correlation
  - headers
  - proxy
handler.chains:
  default:
    exec:
      - correlation
      - headers
      - proxy
handler.paths: []
handler.defaultHandlers:
  - default

proxy.hosts: http://127.0.0.1:8081

llm-router.enabled: false
llm-router.pathPrefix: /v1
