apiVersion: v1
kind: Service
metadata:
  name: ${name}
spec:
  selector:
    app.kubernetes.io/name: ${name}
  ports:
    - name: http
      port: ${service.port:80}
      targetPort: ${containerPort:8080}
