host: ${startup.host:dev.lightapi.net}
serviceId: ${server.serviceId:com.networknt.light-a2a-1.0.0}
envTag: ${server.environment:dev}
acceptHeader: ${startup.acceptHeader:application/yaml}
timeout: ${startup.timeout:3000}
connectTimeout: ${startup.connectTimeout:3000}
configServerUri: ${light-config-server-uri:https://local.lightapi.net}
authorization: ${light_portal_authorization:}
bootstrapCertPath: ${startup.bootstrapCertPath:null}
bootstrapKeyPath: ${startup.bootstrapKeyPath:null}
bootstrapCaCertPath: ${startup.bootstrapCaCertPath:config/ca.pem}
