apiVersion: v1
kind: ConfigMap
metadata:
  name: ${name:ai-microgateway-rust}-config
  namespace: ${namespace:light-gateway}
  labels:
    app.kubernetes.io/name: ${name:ai-microgateway-rust}
    app.kubernetes.io/component: micro-gateway
    app.kubernetes.io/part-of: lightapi
data:
  startup.yml: |
    host: ${startup.host:dev.lightapi.net}
    serviceId: ${startup.serviceId:com.networknt.ai.gateway-1.0.0}
    envTag: ${startup.envTag:dev}
    acceptHeader: application/yaml
    timeout: ${startup.timeout:3000}
    connectTimeout: ${startup.connectTimeout:3000}
    configServerUri: ${configServer.uri:https://light-config-server:8435}
    authorization: "${light_portal_authorization:}"
    bootstrapCaCertPath: ${startup.bootstrapCaCertPath:config/ca.pem}
