apiVersion: v1
kind: Secret
metadata:
  name: ${name:ai-microgateway-rust}-bootstrap
  namespace: ${namespace:light-gateway}
  labels:
    app.kubernetes.io/name: ${name:ai-microgateway-rust}
    app.kubernetes.io/component: micro-gateway
    app.kubernetes.io/part-of: lightapi
type: Opaque
stringData:
  light-portal-authorization: ${lightPortalAuthorization:}
  light-4j-config-password: ${light4jConfigPassword:DEV}
data:
  ca.pem: ${bootstrapCaPemBase64}
