[book]
authors = ["Steve Hu"]
language = "en"
src = "src"
title = "Light-Fabric Documentation"

[output.html]
site-url = "/light-fabric/"
git-repository-url = "https://github.com/networknt/light-fabric"
edit-url-template = "https://github.com/networknt/light-fabric/edit/master/docs/{path}"
