fn main() -> std::io::Result<()> {
    config_embed_build::generate()?;
    validator_build_identity()
}

// Content-derived library/binary build identity, generated by the existing Cargo
// build script. Includes dirty/untracked source, lockfile, compiler, target/profile
// and codegen flags. It is explicitly a reproducible source-build identity, not a
// fabricated version string or a claim that a self-embedded hash is a binary hash.
fn validator_build_identity() -> std::io::Result<()> {
    use sha2::{Digest, Sha256};
    use std::{env, fs, io, path::Path, process::Command};
    let root = std::path::PathBuf::from(env::var("CARGO_MANIFEST_DIR").map_err(io::Error::other)?)
        .join("../..");
    fn collect(root: &Path, dir: &Path, files: &mut Vec<std::path::PathBuf>) -> io::Result<()> {
        for entry in fs::read_dir(dir)? {
            let path = entry?.path();
            if path.is_dir() {
                if !matches!(
                    path.file_name().and_then(|n| n.to_str()),
                    Some("target" | ".git" | ".gitnexus" | "node_modules")
                ) {
                    collect(root, &path, files)?;
                }
            } else if matches!(
                path.extension().and_then(|x| x.to_str()),
                Some("rs" | "toml" | "json" | "yaml" | "yml" | "sql")
            ) || path.file_name().and_then(|x| x.to_str()) == Some("Cargo.lock")
            {
                files.push(
                    path.strip_prefix(root)
                        .map_err(io::Error::other)?
                        .to_owned(),
                );
            }
        }
        Ok(())
    }
    let mut files = vec!["Cargo.toml".into(), "Cargo.lock".into()];
    if root.join(".cargo/config.toml").is_file() {
        files.push(".cargo/config.toml".into());
    }
    for directory in ["apps/light-workflow", "crates", "frameworks"] {
        println!("cargo:rerun-if-changed={}", root.join(directory).display());
        collect(&root, &root.join(directory), &mut files)?;
    }
    files.sort();
    files.dedup();
    let mut hash = Sha256::new();
    for file in files {
        let path = root.join(&file);
        println!("cargo:rerun-if-changed={}", path.display());
        hash.update(file.to_string_lossy().as_bytes());
        hash.update([0]);
        hash.update(Sha256::digest(fs::read(path)?));
    }
    let rustc = Command::new(env::var_os("RUSTC").unwrap_or_else(|| "rustc".into()))
        .arg("-Vv")
        .output()?;
    if !rustc.status.success() {
        return Err(io::Error::other("validator compiler identity unavailable"));
    }
    hash.update(rustc.stdout);
    for key in [
        "TARGET",
        "PROFILE",
        "OPT_LEVEL",
        "DEBUG",
        "CARGO_ENCODED_RUSTFLAGS",
    ] {
        println!("cargo:rerun-if-env-changed={key}");
        hash.update(key.as_bytes());
        hash.update([0]);
        hash.update(env::var(key).unwrap_or_default().as_bytes());
        hash.update([0]);
    }
    let mut features: Vec<_> = env::vars()
        .filter(|(key, _)| key.starts_with("CARGO_FEATURE_"))
        .collect();
    features.sort();
    for (key, value) in features {
        hash.update(key.as_bytes());
        hash.update([0]);
        hash.update(value.as_bytes());
        hash.update([0]);
    }
    println!(
        "cargo:rustc-env=WORKFLOW_VALIDATOR_BUILD=workflow-admission-source-sha256:{:x}",
        hash.finalize()
    );
    Ok(())
}
