tls:
  verifyHostname: ${client.verifyHostname:false}
oauth:
  token:
    key:
      server_url: ${client.tokenKeyServerUrl:}
      serviceId: ${client.tokenKeyServiceId:}
      uri: ${client.tokenKeyUri:/oauth2/key}
      client_id: ${client.tokenKeyClientId:}
      client_secret: ${client.tokenKeyClientSecret:}
      serviceIdAuthServers: ${client.tokenKeyServiceIdAuthServers:{}}
      enableHttp2: ${client.tokenKeyEnableHttp2:true}
      audience: ${client.tokenKeyAudience:}
