host: dev.lightapi.net
serviceId: ${server.serviceId:com.networknt.agent.account-1.0.0}
envTag: ${server.environment:DEV}
acceptHeader: application/yaml
timeout: 3000
connectTimeout: 3000
configServerUri: https://local.lightapi.net
authorization: ${light_portal_authorization:}
bootstrapCaCertPath: config/ca.pem
